name 'dhoppe-apt'
version '0.0.19'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-apt'
source 'git://github.com/dhoppe/puppet-apt'
summary 'APT Module'
description 'APT Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
